[package]
name = "chip8-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fps_clock = "2.0.0"
pixels = "0.11.0"
rand = "0.8.5"
winit = "0.27.5"
winit_input_helper = "0.13.0"
